---
- name: Include nix-default role
  include_role:
    name: utils/nix-default

- name: Add Deadsnakes APT repository
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Install latest deadsnakes python
  apt:
    name:
      - python3.10
      - python 3.10-dev
    state: latest
    update_cache: yes

- name: Installing dependencies for Havoc C2
  apt:
    name:
      - git
      - build-essential
      - apt-utils
      - cmake
      - libfontconfig1
      - libglu1-mesa-dev
      - libgtest-dev
      - libspdlog-dev
      - libboost-all-dev
      - libncurses5-dev
      - libgdbm-dev
      - libssl-dev
      - libreadline-dev
      - libffi-dev
      - libsqlite3-dev
      - libbz2-dev
      - mesa-common-dev
      - qtbase5-dev
      - qtchooser
      - qt5-qmake
      - qtbase5-dev-tools
      - libqt5websockets5
      - libqt5websockets5-dev
      - qtdeclarative5-dev
      - golang-go
      - qtbase5-dev
      - libqt5websockets5-dev
      - python3-dev
      - libboost-all-dev
      - mingw-w64
      - nasm
    state: latest

- name: Clone Havoc C2 repository
  git:
    repo: https://github.com/HavocFramework/Havoc
    dest: /opt/havoc

- name: Building TeamServer prerequisite
  shell: |
      go mod download golang.org/x/sys
      go mod download github.com/ugorji/go
  args:
    chdir: /opt/havoc/teamserver

- name: Building TeamServer
  shell: make ts-build
  args:
    chdir: /opt/havoc

- name: Start Havoc teamserver
  shell: ./havoc server --profile ./profiles/havoc.yaotl -v --debug
  args:
    chdir: /opt/havoc