all:
  vars:
    ansible_user: ubuntu
    ansible_password: ubuntu
    ansible_sudo_pass: "{{ ansible_password }}"
    ansible_shell_type: sh
    zerotoken: <zerotier_token>
    zerotier_network_id: <zerotier_network_id>
  hosts:
    c2-sliver:
      ansible_host: <c2-sliver_ip>
    redirector-caddy:
      ansible_host: <redirector-caddy_ip>
    redirector-caddy-2:
      ansible_host: <redirector-caddy-2_ip>
    operator-nix:
      ansible_host: <operator-nix_ip>
    payload-server:
      ansible_host: <payload-server_ip>