---
- name: Installing dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - gnupg
      - software-properties-common
      - openjdk-11-jdk
      - golang-go
      - git
      - make
      - debian-keyring
      - debian-archive-keyring
    state: latest
    update_cache: yes
    lock_timeout: 120