---
- name: Include nix-default role
  include_role:
    name: utils/nix-default

- name: Update apt cache
  apt:
    update_cache: yes

- name: Check if sliver installed
  stat:
    path: /etc/systemd/system/sliver.service
  register: installed

- name: Download install script for sliver
  get_url:
    url: https://sliver.sh/install
    dest: /tmp/install
    mode: 0755

- name: Install sliver from script
  shell: bash /tmp/install
  when: not installed.stat.exists

- name: Sliver update
  shell: "echo 'update' | sliver"

# for later use
- name: Push sliver config files
  become: true
  template:
    src: "{{ item }}"
    dest: "/root/.sliver/config/{{ item | basename }}"
  with_items:
    - server.json.j2
    - http-c2.json.j2
  ignore_errors: true